# specify a directory to install
cask_args appdir: '/Applications'
# install packages
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'dart-lang/dart'
#tap 'jesseduffield/lazydocker'
tap 'homebrew/cask-fonts'

brew 'ack'
brew 'aria2'
brew 'awscli'
brew 'cmake'
brew 'coreutils'
#brew 'dart'
brew 'docker-compose'
brew 'ffmpeg'
brew 'fzf'
brew 'gettext'
brew 'gifify'
brew 'gifsicle'
brew 'git'
brew 'git-extras'
brew 'git-secrets'
brew 'glances'
brew 'gnupg'
brew 'graphviz'
brew 'harfbuzz'
brew 'htop'
brew 'hub'
brew 'imagemagick'
brew 'jsonlint'
brew 'jq'
brew 'lazydocker'
brew 'lazygit'
brew 'libksba'
brew 'libmagic'
brew 'libxml2'
brew 'libxmlsec1'
brew 'libssh2'
brew 'libyaml'
brew 'links'
brew 'mas'
brew 'midnight-commander'
brew 'mpv'
brew 'mtr'
brew 'mysql', restart_service: true
brew 'ncdu'
brew 'nmap'
brew 'nodenv'
brew 'nvm'
brew 'openssl'
brew 'pixman'
brew 'postgresql', restart_service: true
brew 'python'
brew 'pyqt'
brew 'pyenv-virtualenv'
brew 'pv'
brew 'pwgen'
brew 'readline'
brew 'redis'
brew 'ruby'
brew 'scrcpy'
brew 'speedtest_cli'
brew 'telnet'
brew 'tig'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'unar'
brew 'v8-315'
brew 'websocat'
brew 'wget'
brew 'xvid'
brew 'xz'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'zplug'

cask 'alfred'
cask 'browserosaurus'
cask 'calibre'
cask 'disk-inventory-x'
cask 'docker'
cask 'dropbox'
cask 'epic-games'
cask 'fantastical'
#cask 'flutter'
cask 'flux'
cask 'font-hack-nerd-font'
cask 'github'
cask 'google-chrome'
cask 'iterm2'
cask 'licecap'
cask 'phoenix-slides'
cask 'postman'
cask 'quitter'
cask 'raspberry-pi-imager'
cask 'send-to-kindle'
cask 'steam'
cask 'tomighty'
cask 'telegram'
cask 'ubersicht'
cask 'visual-studio-code'
cask 'vlc'

mas 'Amphetamine', id: 937984704
mas 'Dropzone 3', id: 695406827
mas 'Kindle', id: 405399194
mas 'Magnet', id: 441258766
mas 'PopClip', id: 445189367
mas 'ScreenFloat', id: 414528154
mas 'Yoink', id: 457622435

# exec 'softwareupdate -i -a'
